### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by enguerran** [bosonic/bosonic.github.io#12]
Just an issue to see if translations are wanted or not.
I know a lot of people won't read english and will wait for content in their language (see mdn in french). For sample, who wants a french version?

Une petite requête pour voir si des traductions sont attendues ou pas.
Je sais que beaucoup de personnes ne lisent pas l'anglais et vont attendre que le contenu soit disponible dans leur langue (voir mdn en français). Par exemple, qui voudrait voir une version française ?

**Comment by JulienItard** [comment]
Perso je pense que les gens sont suffisamment habitués à lire des documents techniques du genre en anglais.

**Comment by goldoraf** [comment]
Let's see what people think! But before translating the whole documentation, I think that writing a good tutorial in french could help a lot ;)

**Comment by enguerran** [comment]
@JulienItard Que #lesgens soient habitués à lire de la doc en anglais, je ne dis pas. Qu'ils aient des réticences à se lancer car la lecture en anglais demandant plus d'effort, là je dis.

And so I :+1: @goldoraf idea about a good French tutorial. Easier than maintaining different languages on the website.
