### ISSUE TITLE
Grunt server errors

### ISSUE THREAD

**Issue by JulienItard** [bosonic/bosonic.github.io#13]
Hi there,

i'd like to contribute but when i clone the repo, npm install and grunt server i have the following error: 

julien@julien-pc ~/Labs/Bosonic/bosonic.github.io $ grunt
Loading "compass.js" tasks...ERROR
>> Error: Cannot find module 'bin-version-check'
Loading "connect.js" tasks...ERROR
>> Error: Cannot find module 'connect'
Loading "watch.js" tasks...ERROR
>> Error: Cannot find module 'gaze'
Loading "curl.js" tasks...ERROR
>> Error: Cannot find module 'grunt-retro'
Loading "gh-pages.js" tasks...ERROR
>> Error: Cannot find module 'q'
Loading "open.js" tasks...ERROR
>> Error: Cannot find module 'open'
Loading "pages.js" tasks...ERROR
>> Error: Cannot find module 'colors'
Loading "repos.js" tasks...ERROR
>> Error: Cannot find module 'async'
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'each-async'
Warning: Task "connect" not found. Use --force to continue.

**Comment by goldoraf** [comment]
Wow, that's weird... I just did a test (cloning then npm install) and it works like a charm :/ Is your node install OK? Could you give me more details?

Btw, I updated the README, installing the ruby version of compass is no longer necessary, a simple npm install is sufficient.

**Comment by JulienItard** [comment]
node : 1.4.14
npm : 0.10.29
grunt : 0.1.13
sass : 3.4.18

**Comment by enguerran** [comment]
It may be related to https://github.com/sass/node-sass/issues/696 and https://github.com/sass/node-sass/issues/1061, aka `npm version`.

What's the output of `npm version` required to install and run the website?

Here's mine:
```
% npm version
{ 'cabin-site': '0.0.0',
  npm: '3.3.4',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.1',
  openssl: '1.0.2d',
  uv: '1.7.4',
  v8: '4.5.103.33',
  zlib: '1.2.8' }
```

**Comment by JulienItard** [comment]
Here is mine : 

{ 'cabin-site': '0.0.0',
  npm: '3.3.4',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.0.0',
  openssl: '1.0.2d',
  uv: '1.7.3',
  v8: '4.5.103.30',
  zlib: '1.2.8' }

**Comment by enguerran** [comment]
With `node 0.12`, it works like a charm.
As it depends on 3rd party dependency (node-sass), I think we can close this issue and open a new one called: "make it work with node 4.x" which could be fixed by changing grunt task for building css.

For information, here is my `npm version`:

```
% npm version                                                                                                                                                            130 ↵
{ 'cabin-site': '0.0.0',
  npm: '3.3.6',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.2d',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```
