### ISSUE TITLE
make it work with node 4.x

### ISSUE THREAD

**Issue by enguerran** [bosonic/bosonic.github.io#14]
Regarding #13 it seems that the website is not ready for node 4.x / npm 3.x (see https://github.com/sass/node-sass/issues/1061). We need some experimentation to see what to do to build the website with this configuration.

**Comment by goldoraf** [comment]
It looks like recent versions of node-sass and grunt-sass work better with node 4.x. As I have a lot of things to work on currently, I don't want to upgrade node now and take the risk to damage my environment. If you have time, could you try to update node-sass and grunt-sass versions and see if it works?
